In [1]:
#importing os library
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#changing the work directory
os.chdir('/Users/sushovanmandal/Documents/code/learn-gen-ai/analyticsVidhya genAI/Foundational ML Algorithams')

In [4]:
healthcare_data = pd.read_csv("Healthcare_Dataset_Preprocessed.csv")
healthcare_data.head().transpose()

                          0      1      2      3      4
Age                     2.0    8.0   81.0   25.0   24.0
BMI                    26.0   24.0   27.0   21.0   26.0
Blood_Pressure        111.0  121.0  147.0  150.0  146.0
Cholesterol           198.0  199.0  203.0  199.0  202.0
Glucose_Level          99.0  103.0  100.0  102.0   99.0
Heart_Rate             72.0   75.0   74.0   70.0   76.0
Sleep_Hours             4.0    2.0   10.0    7.0   10.0
Exercise_Hours          1.0    1.0   -0.0    3.0    2.0
Water_Intake            5.0    2.0    5.0    3.0    5.0
Stress_Level            5.0    9.0    1.0    3.0    1.0
Target                  1.0    1.0    0.0    0.0    0.0
Smoking                 2.0    0.0    2.0    2.0    0.0
Alcohol                 2.0    1.0    1.0    0.0    1.0
Diet                    1.0    1.0    2.0    1.0    2.0
MentalHealth            2.0    2.0    0.0    2.0    0.0
PhysicalActivity        1.0    1.0    0.0    1.0    2.0
MedicalHistory          0.0    2.0    1.0    2.0    0.0
Allergies               1.0    2.0    0.0    0.0    2.0
Diet_Type_Vegan         0.0    0.0    1.0    1.0    0.0
Diet_Type_Vegetarian    1.0    0.0    0.0    0.0    1.0
Blood_Group_AB          1.0    1.0    0.0    0.0    0.0
Blood_Group_B           0.0    0.0    0.0    1.0    1.0
Blood_Group_O           0.0    0.0    0.0    0.0    0.0

In [5]:
healthcare_data.shape

(9549, 23)

In [6]:
healthcare_data.dtypes

Age                     float64
BMI                     float64
Blood_Pressure          float64
Cholesterol             float64
Glucose_Level           float64
Heart_Rate              float64
Sleep_Hours             float64
Exercise_Hours          float64
Water_Intake            float64
Stress_Level            float64
Target                    int64
Smoking                   int64
Alcohol                   int64
Diet                      int64
MentalHealth              int64
PhysicalActivity          int64
MedicalHistory            int64
Allergies                 int64
Diet_Type_Vegan           int64
Diet_Type_Vegetarian      int64
Blood_Group_AB            int64
Blood_Group_B             int64
Blood_Group_O             int64
dtype: object

In [7]:
healthcare_data.describe()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,...,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,25.660697,130.382658,199.091528,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,...,1.005864,0.998429,1.003351,1.004713,0.989318,0.329354,0.335742,0.244947,0.253849,0.252592
std,24.566473,1.942369,27.878476,1.969234,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,...,0.815877,0.821844,0.808800,0.813506,0.815699,0.470003,0.472274,0.430078,0.435235,0.434522
min,0.000000,19.000000,22.000000,192.000000,93.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,24.000000,113.000000,198.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,26.000000,134.000000,199.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,50.000000,27.000000,150.000000,200.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,100.000000,32.000000,225.000000,207.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000

There are no null values in this dataset

In [9]:
healthcare_data.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Cholesterol             0
Glucose_Level           0
Heart_Rate              0
Sleep_Hours             0
Exercise_Hours          0
Water_Intake            0
Stress_Level            0
Target                  0
Smoking                 0
Alcohol                 0
Diet                    0
MentalHealth            0
PhysicalActivity        0
MedicalHistory          0
Allergies               0
Diet_Type_Vegan         0
Diet_Type_Vegetarian    0
Blood_Group_AB          0
Blood_Group_B           0
Blood_Group_O           0
dtype: int64

# Convert BMI to categorical

In [11]:
hdf = healthcare_data

In [12]:
# Step 1: Define bmi bins and labels, since min BMI is 19, we don't have to deal with underweight
bins = [0, 25, 30, 100]        # lower bounds: <25, 25–29.9, 30–100
labels = [0, 1, 2]
hdf['bmi_cat'] = pd.cut(hdf['BMI'], bins=bins, labels=labels, include_lowest=True, right=False)

In [13]:
hdf.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,2,1,0,1,0,1,1,0,0,1
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,2,1,2,2,0,0,1,0,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,0,0,1,0,1,0,0,0,0,1
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,2,1,2,0,1,0,0,1,0,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,0,2,0,2,0,1,0,1,0,1

In [14]:
hdf.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Cholesterol             0
Glucose_Level           0
Heart_Rate              0
Sleep_Hours             0
Exercise_Hours          0
Water_Intake            0
Stress_Level            0
Target                  0
Smoking                 0
Alcohol                 0
Diet                    0
MentalHealth            0
PhysicalActivity        0
MedicalHistory          0
Allergies               0
Diet_Type_Vegan         0
Diet_Type_Vegetarian    0
Blood_Group_AB          0
Blood_Group_B           0
Blood_Group_O           0
bmi_cat                 0
dtype: int64

In [15]:
hdf = hdf.drop(columns=['BMI'])

In [16]:
hdf.head()

,Age,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,...,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat
0,2.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,1,...,2,1,0,1,0,1,1,0,0,1
1,8.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,1,...,2,1,2,2,0,0,1,0,0,0
2,81.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,...,0,0,1,0,1,0,0,0,0,1
3,25.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,0,...,2,1,2,0,1,0,0,1,0,0
4,24.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,0,...,0,2,0,2,0,1,0,1,0,1

# Convert Cholesterol to categorical

In [17]:
hdf.loc[hdf['Cholesterol'] < 200, 'chol_cat'] = 0

In [18]:
hdf.loc[hdf['Cholesterol'] >= 200, 'chol_cat'] = 1

In [19]:
hdf = hdf.drop(columns=['Cholesterol'])

In [20]:
hdf.head()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,...,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat
0,2.0,111.0,99.0,72.0,4.0,1.0,5.0,5.0,1,2,...,1,0,1,0,1,1,0,0,1,0.0
1,8.0,121.0,103.0,75.0,2.0,1.0,2.0,9.0,1,0,...,1,2,2,0,0,1,0,0,0,0.0
2,81.0,147.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,2,...,0,1,0,1,0,0,0,0,1,1.0
3,25.0,150.0,102.0,70.0,7.0,3.0,3.0,3.0,0,2,...,1,2,0,1,0,0,1,0,0,0.0
4,24.0,146.0,99.0,76.0,10.0,2.0,5.0,1.0,0,0,...,2,0,2,0,1,0,1,0,1,1.0

In [21]:
hdf.describe()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,...,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,chol_cat
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,...,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,130.382658,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,...,0.998429,1.003351,1.004713,0.989318,0.329354,0.335742,0.244947,0.253849,0.252592,0.395225
std,24.566473,27.878476,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,...,0.821844,0.808800,0.813506,0.815699,0.470003,0.472274,0.430078,0.435235,0.434522,0.488924
min,0.000000,22.000000,93.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,113.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,134.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,50.000000,150.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
max,100.000000,225.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# Convert Glucose to categorical

In [22]:
hdf.loc[hdf['Glucose_Level'] < 100, 'gluco_cat'] = 0

In [23]:
hdf.loc[hdf['Glucose_Level'] >= 100, 'gluco_cat'] = 1

In [24]:
hdf.head()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,...,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat,gluco_cat
0,2.0,111.0,99.0,72.0,4.0,1.0,5.0,5.0,1,2,...,0,1,0,1,1,0,0,1,0.0,0.0
1,8.0,121.0,103.0,75.0,2.0,1.0,2.0,9.0,1,0,...,2,2,0,0,1,0,0,0,0.0,1.0
2,81.0,147.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,2,...,1,0,1,0,0,0,0,1,1.0,1.0
3,25.0,150.0,102.0,70.0,7.0,3.0,3.0,3.0,0,2,...,2,0,1,0,0,1,0,0,0.0,1.0
4,24.0,146.0,99.0,76.0,10.0,2.0,5.0,1.0,0,0,...,0,2,0,1,0,1,0,1,1.0,0.0

In [25]:
hdf = hdf.drop(columns=['Glucose_Level'])

In [26]:
hdf.describe()

,Age,Blood_Pressure,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,...,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,chol_cat,gluco_cat
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,...,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,130.382658,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,...,1.003351,1.004713,0.989318,0.329354,0.335742,0.244947,0.253849,0.252592,0.395225,0.647398
std,24.566473,27.878476,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,...,0.808800,0.813506,0.815699,0.470003,0.472274,0.430078,0.435235,0.434522,0.488924,0.477805
min,0.000000,22.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,113.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,134.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,50.000000,150.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
max,100.000000,225.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# shuffle dataset

In [27]:
hdf_final = hdf.sample(frac = 1, random_state=1)

In [28]:
hdf_final.head()

,Age,Blood_Pressure,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,...,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat,gluco_cat
8287,73.0,99.0,74.0,7.0,2.0,3.0,4.0,1,1,1,...,0,0,0,1,0,0,0,1,0.0,1.0
3601,39.0,151.0,71.0,7.0,2.0,6.0,5.0,1,0,0,...,0,0,0,0,0,0,1,1,0.0,1.0
8222,2.0,69.0,73.0,5.0,1.0,5.0,6.0,1,2,2,...,0,1,1,0,0,0,0,1,0.0,1.0
3305,52.0,103.0,76.0,8.0,3.0,1.0,5.0,1,1,2,...,1,2,0,1,0,0,1,1,1.0,1.0
218,31.0,207.0,74.0,10.0,4.0,8.0,-0.0,0,2,2,...,0,2,0,0,0,0,1,0,1.0,1.0

In [29]:
hdf.shape, hdf_final.shape

((9549, 23), (9549, 23))

# Prepare Data

In [30]:
#Separating the independent and target variables
y = hdf_final['Target']
X = hdf_final.drop(columns = ['Target'], axis = 1)

In [31]:
X.head().transpose()

                      8287   3601  8222   3305   218
Age                   73.0   39.0   2.0   52.0   31.0
Blood_Pressure        99.0  151.0  69.0  103.0  207.0
Heart_Rate            74.0   71.0  73.0   76.0   74.0
Sleep_Hours            7.0    7.0   5.0    8.0   10.0
Exercise_Hours         2.0    2.0   1.0    3.0    4.0
Water_Intake           3.0    6.0   5.0    1.0    8.0
Stress_Level           4.0    5.0   6.0    5.0   -0.0
Smoking                1.0    0.0   2.0    1.0    2.0
Alcohol                1.0    0.0   2.0    2.0    2.0
Diet                   1.0    2.0   1.0    2.0    0.0
MentalHealth           2.0    1.0   1.0    2.0    0.0
PhysicalActivity       1.0    2.0   2.0    2.0    2.0
MedicalHistory         0.0    0.0   0.0    1.0    0.0
Allergies              0.0    0.0   1.0    2.0    2.0
Diet_Type_Vegan        0.0    0.0   1.0    0.0    0.0
Diet_Type_Vegetarian   1.0    0.0   0.0    1.0    0.0
Blood_Group_AB         0.0    0.0   0.0    0.0    0.0
Blood_Group_B          0.0    0.0   0.0    0.0    0.0
Blood_Group_O          0.0    1.0   0.0    1.0    1.0
bmi_cat                1.0    1.0   1.0    1.0    0.0
chol_cat               0.0    0.0   0.0    1.0    1.0
gluco_cat              1.0    1.0   1.0    1.0    1.0

In [34]:
#import libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [35]:
#split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [36]:
#A quick look at the shape of the datasets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6684, 22), (2865, 22), (6684,), (2865,))

In [37]:
logreg = LogisticRegression()

In [38]:
logreg.fit(X_train, y_train)

/opt/miniconda3/envs/pg_python_ai/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [39]:
#making predictions on the same training data
y_train_pred = logreg.predict(X_train)

In [40]:
#making predictions on the test data based on the learniing from fitting model on the train data
y_pred = logreg.predict(X_test)

In [41]:
#import confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
# Generate the confusion matrix for train data
train_cm = confusion_matrix(y_train, y_train_pred)

print("Confusion Matrix for Train Set:")
print(train_cm)

Confusion Matrix for Train Set:
[[2510  717]
 [ 749 2708]]

In our case, when we create the confusion matrix for train data - 
- True Negative is 2510
- False Positive is 717
- False Negative is 749 and 
- True Positive is 2708

In [43]:
# Generate the confusion matrix for test data
test_cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix for Test Set:")
print(test_cm)

Confusion Matrix for Test Set:
[[1038  305]
 [ 322 1200]]

In [44]:
accuracy_score(y_train, y_train_pred)

0.7806702573309395

In [45]:
accuracy_score(y_test, y_pred)

0.7811518324607329

In [46]:
#calculating precision on train set
from sklearn.metrics import precision_score
train_precision = precision_score(y_train, y_train_pred)
print(train_precision)

0.7906569343065694

In [47]:
#calculating precision on test set
test_precision = precision_score(y_test, y_pred)
print(test_precision)

0.7973421926910299

In [48]:
#calculating recall on train set
from sklearn.metrics import recall_score
train_recall = recall_score(y_train, y_train_pred)
print(train_recall)

0.783338154469193

In [49]:
#calculating recall on test set
test_recall = recall_score(y_test, y_pred)
print(test_recall)

0.7884362680683311

In [50]:
#calculating f1_score on train set
from sklearn.metrics import f1_score
train_f1 = f1_score(y_train, y_train_pred)
print(train_f1)

0.7869805289160128

In [51]:
#calculating precision on test set
test_f1 = f1_score(y_test, y_pred)
print(test_f1)

0.7928642220019821

In [52]:
#create classification for train set
from sklearn.metrics import classification_report
train_classification_report = classification_report(y_train, y_train_pred)
print(train_classification_report)

              precision    recall  f1-score   support

           0       0.77      0.78      0.77      3227
           1       0.79      0.78      0.79      3457

    accuracy                           0.78      6684
   macro avg       0.78      0.78      0.78      6684
weighted avg       0.78      0.78      0.78      6684

In [53]:
#create classification for test set
from sklearn.metrics import classification_report
test_classification_report = classification_report(y_test, y_pred)
print(test_classification_report)

              precision    recall  f1-score   support

           0       0.76      0.77      0.77      1343
           1       0.80      0.79      0.79      1522

    accuracy                           0.78      2865
   macro avg       0.78      0.78      0.78      2865
weighted avg       0.78      0.78      0.78      2865