In [1]:
#importing os library
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#changing the work directory
os.chdir('/Users/sushovanmandal/Documents/code/learn-gen-ai/analyticsVidhya genAI/Foundational ML Algorithams')

In [3]:
healthcare_data = pd.read_csv("Healthcare_Dataset_Preprocessed_DT.csv")
healthcare_data.head().transpose()

                          0      1      2      3      4
Age                     2.0    8.0   81.0   25.0   24.0
BMI                    26.0   24.0   27.0   21.0   26.0
Blood_Pressure        111.0  121.0  147.0  150.0  146.0
Cholesterol           198.0  199.0  203.0  199.0  202.0
Glucose_Level          99.0  103.0  100.0  102.0   99.0
Heart_Rate             72.0   75.0   74.0   70.0   76.0
Sleep_Hours             4.0    2.0   10.0    7.0   10.0
Exercise_Hours          1.0    1.0   -0.0    3.0    2.0
Water_Intake            5.0    2.0    5.0    3.0    5.0
Stress_Level            5.0    9.0    1.0    3.0    1.0
Target                    1      1      0      0      0
Smoking                   2      0      2      2      0
Alcohol                   2      1      1      0      1
Diet                      1      1      2      1      2
MentalHealth              2      2      0      2      0
PhysicalActivity          1      1      0      1      2
MedicalHistory            0      2      1      2      0
Allergies                 1      2      0      0      2
Diet_Type_Vegan       False  False   True   True  False
Diet_Type_Vegetarian   True  False  False  False   True
Blood_Group_AB         True   True  False  False  False
Blood_Group_B         False  False  False   True   True
Blood_Group_O         False  False  False  False  False

In [4]:
healthcare_data.shape

(9549, 23)

In [5]:
healthcare_data.dtypes

Age                     float64
BMI                     float64
Blood_Pressure          float64
Cholesterol             float64
Glucose_Level           float64
Heart_Rate              float64
Sleep_Hours             float64
Exercise_Hours          float64
Water_Intake            float64
Stress_Level            float64
Target                    int64
Smoking                   int64
Alcohol                   int64
Diet                      int64
MentalHealth              int64
PhysicalActivity          int64
MedicalHistory            int64
Allergies                 int64
Diet_Type_Vegan            bool
Diet_Type_Vegetarian       bool
Blood_Group_AB             bool
Blood_Group_B              bool
Blood_Group_O              bool
dtype: object

In [6]:
healthcare_data.describe()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,25.660697,130.382658,199.091528,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318
std,24.566473,1.942369,27.878476,1.969234,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699
min,0.000000,19.000000,22.000000,192.000000,93.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,24.000000,113.000000,198.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,26.000000,134.000000,199.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,50.000000,27.000000,150.000000,200.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,100.000000,32.000000,225.000000,207.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

There are no null values in this dataset

In [7]:
healthcare_data.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Cholesterol             0
Glucose_Level           0
Heart_Rate              0
Sleep_Hours             0
Exercise_Hours          0
Water_Intake            0
Stress_Level            0
Target                  0
Smoking                 0
Alcohol                 0
Diet                    0
MentalHealth            0
PhysicalActivity        0
MedicalHistory          0
Allergies               0
Diet_Type_Vegan         0
Diet_Type_Vegetarian    0
Blood_Group_AB          0
Blood_Group_B           0
Blood_Group_O           0
dtype: int64

# Convert BMI to categorical

In [8]:
hdf = healthcare_data

In [9]:
# Step 1: Define bmi bins and labels, since min BMI is 19, we don't have to deal with underweight
bins = [0, 25, 30, 100]        # lower bounds: <25, 25–29.9, 30–100
labels = [0, 1, 2]
hdf['bmi_cat'] = pd.cut(hdf['BMI'], bins=bins, labels=labels, include_lowest=True, right=False)

In [10]:
hdf.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,2,1,0,1,False,True,True,False,False,1
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,2,1,2,2,False,False,True,False,False,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,0,0,1,0,True,False,False,False,False,1
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,2,1,2,0,True,False,False,True,False,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,0,2,0,2,False,True,False,True,False,1

In [11]:
hdf.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Cholesterol             0
Glucose_Level           0
Heart_Rate              0
Sleep_Hours             0
Exercise_Hours          0
Water_Intake            0
Stress_Level            0
Target                  0
Smoking                 0
Alcohol                 0
Diet                    0
MentalHealth            0
PhysicalActivity        0
MedicalHistory          0
Allergies               0
Diet_Type_Vegan         0
Diet_Type_Vegetarian    0
Blood_Group_AB          0
Blood_Group_B           0
Blood_Group_O           0
bmi_cat                 0
dtype: int64

In [12]:
hdf = hdf.drop(columns=['BMI'])

In [13]:
hdf.head()

,Age,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,...,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat
0,2.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,1,...,2,1,0,1,False,True,True,False,False,1
1,8.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,1,...,2,1,2,2,False,False,True,False,False,0
2,81.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,...,0,0,1,0,True,False,False,False,False,1
3,25.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,0,...,2,1,2,0,True,False,False,True,False,0
4,24.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,0,...,0,2,0,2,False,True,False,True,False,1

# Convert Cholesterol to categorical

In [14]:
hdf.loc[hdf['Cholesterol'] < 200, 'chol_cat'] = 0

In [15]:
hdf.loc[hdf['Cholesterol'] >= 200, 'chol_cat'] = 1

In [16]:
hdf = hdf.drop(columns=['Cholesterol'])

In [17]:
hdf.head()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,...,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat
0,2.0,111.0,99.0,72.0,4.0,1.0,5.0,5.0,1,2,...,1,0,1,False,True,True,False,False,1,0.0
1,8.0,121.0,103.0,75.0,2.0,1.0,2.0,9.0,1,0,...,1,2,2,False,False,True,False,False,0,0.0
2,81.0,147.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,2,...,0,1,0,True,False,False,False,False,1,1.0
3,25.0,150.0,102.0,70.0,7.0,3.0,3.0,3.0,0,2,...,1,2,0,True,False,False,True,False,0,0.0
4,24.0,146.0,99.0,76.0,10.0,2.0,5.0,1.0,0,0,...,2,0,2,False,True,False,True,False,1,1.0

In [18]:
hdf.describe()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,chol_cat
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,130.382658,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318,0.395225
std,24.566473,27.878476,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699,0.488924
min,0.000000,22.000000,93.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,113.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,134.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
75%,50.000000,150.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000
max,100.000000,225.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000

# Convert Glucose to categorical

In [19]:
hdf.loc[hdf['Glucose_Level'] < 100, 'gluco_cat'] = 0

In [20]:
hdf.loc[hdf['Glucose_Level'] >= 100, 'gluco_cat'] = 1

In [21]:
hdf.head()

,Age,Blood_Pressure,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,...,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat,gluco_cat
0,2.0,111.0,99.0,72.0,4.0,1.0,5.0,5.0,1,2,...,0,1,False,True,True,False,False,1,0.0,0.0
1,8.0,121.0,103.0,75.0,2.0,1.0,2.0,9.0,1,0,...,2,2,False,False,True,False,False,0,0.0,1.0
2,81.0,147.0,100.0,74.0,10.0,-0.0,5.0,1.0,0,2,...,1,0,True,False,False,False,False,1,1.0,1.0
3,25.0,150.0,102.0,70.0,7.0,3.0,3.0,3.0,0,2,...,2,0,True,False,False,True,False,0,0.0,1.0
4,24.0,146.0,99.0,76.0,10.0,2.0,5.0,1.0,0,0,...,0,2,False,True,False,True,False,1,1.0,0.0

In [22]:
hdf = hdf.drop(columns=['Glucose_Level'])

In [23]:
hdf.describe()

,Age,Blood_Pressure,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,chol_cat,gluco_cat
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,130.382658,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318,0.395225,0.647398
std,24.566473,27.878476,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699,0.488924,0.477805
min,0.000000,22.000000,67.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,113.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,134.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
75%,50.000000,150.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000
max,100.000000,225.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000

# shuffle dataset

In [24]:
hdf_final = hdf.sample(frac = 1, random_state=1)

In [25]:
hdf_final.head()

,Age,Blood_Pressure,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,...,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O,bmi_cat,chol_cat,gluco_cat
8287,73.0,99.0,74.0,7.0,2.0,3.0,4.0,1,1,1,...,0,0,False,True,False,False,False,1,0.0,1.0
3601,39.0,151.0,71.0,7.0,2.0,6.0,5.0,1,0,0,...,0,0,False,False,False,False,True,1,0.0,1.0
8222,2.0,69.0,73.0,5.0,1.0,5.0,6.0,1,2,2,...,0,1,True,False,False,False,False,1,0.0,1.0
3305,52.0,103.0,76.0,8.0,3.0,1.0,5.0,1,1,2,...,1,2,False,True,False,False,True,1,1.0,1.0
218,31.0,207.0,74.0,10.0,4.0,8.0,-0.0,0,2,2,...,0,2,False,False,False,False,True,0,1.0,1.0

In [26]:
hdf.shape, hdf_final.shape

((9549, 23), (9549, 23))

# Prepare Data

In [28]:
hdf_final['Target'].value_counts(normalize=True)

Target
1    0.521416
0    0.478584
Name: proportion, dtype: float64

Roughly similar proportion of classes here

In [29]:
#Separating the independent and target variables
y = hdf_final['Target']
X = hdf_final.drop(columns = ['Target'], axis = 1)

In [30]:
X.head().transpose()

                       8287   3601   8222   3305   218
Age                    73.0   39.0    2.0   52.0   31.0
Blood_Pressure         99.0  151.0   69.0  103.0  207.0
Heart_Rate             74.0   71.0   73.0   76.0   74.0
Sleep_Hours             7.0    7.0    5.0    8.0   10.0
Exercise_Hours          2.0    2.0    1.0    3.0    4.0
Water_Intake            3.0    6.0    5.0    1.0    8.0
Stress_Level            4.0    5.0    6.0    5.0   -0.0
Smoking                   1      0      2      1      2
Alcohol                   1      0      2      2      2
Diet                      1      2      1      2      0
MentalHealth              2      1      1      2      0
PhysicalActivity          1      2      2      2      2
MedicalHistory            0      0      0      1      0
Allergies                 0      0      1      2      2
Diet_Type_Vegan       False  False   True  False  False
Diet_Type_Vegetarian   True  False  False   True  False
Blood_Group_AB        False  False  False  False  False
Blood_Group_B         False  False  False  False  False
Blood_Group_O         False   True  False   True   True
bmi_cat                   1      1      1      1      0
chol_cat                0.0    0.0    0.0    1.0    1.0
gluco_cat               1.0    1.0    1.0    1.0    1.0

In [31]:
#import libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

Let's stratify the train test split

In [32]:
#split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 42)

In [33]:
#A quick look at the shape of the datasets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6684, 22), (2865, 22), (6684,), (2865,))

In [36]:
y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(Target
 1    0.521394
 0    0.478606
 Name: proportion, dtype: float64,
 Target
 1    0.521466
 0    0.478534
 Name: proportion, dtype: float64)

# Train Decision Tree on data

Let's apply class_Weight = 'balanced' for the Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(random_state=42, class_weight = 'balanced')

In [39]:
DT_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [40]:
#making predictions on the same training data
y_train_pred = DT_model.predict(X_train)

In [41]:
#making predictions on the test data based on the learniing from fitting model on the train data
y_pred = DT_model.predict(X_test)

In [42]:
#import confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score

In [43]:
# Generate the confusion matrix for train data
train_cm = confusion_matrix(y_train, y_train_pred)

print("Confusion Matrix for Train Set:")
print(train_cm)

Confusion Matrix for Train Set:
[[3199    0]
 [   0 3485]]

In [44]:
# Generate the confusion matrix for test data
test_cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix for Test Set:")
print(test_cm)

Confusion Matrix for Test Set:
[[1173  198]
 [ 221 1273]]

In [45]:
accuracy_score(y_train, y_train_pred)

1.0

In [46]:
accuracy_score(y_test, y_pred)

0.8537521815008726

In [47]:
#calculating precision on train set
from sklearn.metrics import precision_score
train_precision = precision_score(y_train, y_train_pred)
print(train_precision)

1.0

In [48]:
#calculating precision on test set
test_precision = precision_score(y_test, y_pred)
print(test_precision)

0.8653976886471788

In [49]:
#calculating recall on train set
from sklearn.metrics import recall_score
train_recall = recall_score(y_train, y_train_pred)
print(train_recall)

1.0

In [50]:
#calculating recall on test set
test_recall = recall_score(y_test, y_pred)
print(test_recall)

0.8520749665327979

In [51]:
#calculating f1_score on train set
from sklearn.metrics import f1_score
train_f1 = f1_score(y_train, y_train_pred)
print(train_f1)

1.0

In [52]:
#calculating precision on test set
test_f1 = f1_score(y_test, y_pred)
print(test_f1)

0.8586846543001686

In [53]:
#create classification for train set
from sklearn.metrics import classification_report
train_classification_report = classification_report(y_train, y_train_pred)
print(train_classification_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3199
           1       1.00      1.00      1.00      3485

    accuracy                           1.00      6684
   macro avg       1.00      1.00      1.00      6684
weighted avg       1.00      1.00      1.00      6684

In [54]:
#create classification for test set
from sklearn.metrics import classification_report
test_classification_report = classification_report(y_test, y_pred)
print(test_classification_report)

              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1371
           1       0.87      0.85      0.86      1494

    accuracy                           0.85      2865
   macro avg       0.85      0.85      0.85      2865
weighted avg       0.85      0.85      0.85      2865

It is an overfitting model

## Calculate feature importance

In [55]:
#Retreiving the importance score of each feature
feature_imp = DT_model.feature_importances_

In [56]:
# Sorting the features by importance in descending order in a dataframe.
imp = pd.DataFrame({'Col_names': X_train.columns, 'Importance': np.round(feature_imp, 2)})\
.sort_values(by='Importance', ascending=False)
imp

               Col_names  Importance
19               bmi_cat        0.18
1         Blood_Pressure        0.15
20              chol_cat        0.13
6           Stress_Level        0.11
0                    Age        0.08
3            Sleep_Hours        0.07
2             Heart_Rate        0.06
5           Water_Intake        0.06
21             gluco_cat        0.04
4         Exercise_Hours        0.04
13             Allergies        0.02
9                   Diet        0.01
10          MentalHealth        0.01
8                Alcohol        0.01
12        MedicalHistory        0.01
17         Blood_Group_B        0.01
7                Smoking        0.01
14       Diet_Type_Vegan        0.00
15  Diet_Type_Vegetarian        0.00
16        Blood_Group_AB        0.00
18         Blood_Group_O        0.00
11      PhysicalActivity        0.00

In [57]:
# Calculating the cumulative sum of the 'Importance' column and store it in a new column called 'cum_imp'
imp['cum_imp'] = imp.Importance.cumsum()
imp

               Col_names  Importance  cum_imp
19               bmi_cat        0.18     0.18
1         Blood_Pressure        0.15     0.33
20              chol_cat        0.13     0.46
6           Stress_Level        0.11     0.57
0                    Age        0.08     0.65
3            Sleep_Hours        0.07     0.72
2             Heart_Rate        0.06     0.78
5           Water_Intake        0.06     0.84
21             gluco_cat        0.04     0.88
4         Exercise_Hours        0.04     0.92
13             Allergies        0.02     0.94
9                   Diet        0.01     0.95
10          MentalHealth        0.01     0.96
8                Alcohol        0.01     0.97
12        MedicalHistory        0.01     0.98
17         Blood_Group_B        0.01     0.99
7                Smoking        0.01     1.00
14       Diet_Type_Vegan        0.00     1.00
15  Diet_Type_Vegetarian        0.00     1.00
16        Blood_Group_AB        0.00     1.00
18         Blood_Group_O        0.00     1.00
11      PhysicalActivity        0.00     1.00

In [58]:
# Selecting the columns with cumulative importance exceeding 0.99 and create a list of column names to drop
drop_col = imp[imp.cum_imp >=  0.99]['Col_names'].to_list()
drop_col

['Blood_Group_B',
 'Smoking',
 'Diet_Type_Vegan',
 'Diet_Type_Vegetarian',
 'Blood_Group_AB',
 'Blood_Group_O',
 'PhysicalActivity']

## Dropping irrelevant features

In [59]:
# Dropping the columns from X_train
X_train.drop(columns = drop_col, axis = 1, inplace = True)

# Dropping the columns from X_test
X_test.drop(columns = drop_col, axis = 1, inplace = True)

# Training model on relevant columns

In [60]:
DT_model = DecisionTreeClassifier(random_state=42, class_weight = 'balanced')

In [61]:
DT_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [62]:
# Making the predictions using the modified X_test
y_pred_train = DT_model.predict(X_train)
y_pred = DT_model.predict(X_test)

In [63]:
#Classification report on train data
class_report_test = classification_report(y_train,y_pred_train)
print ("The train report is:")
print (class_report_test)

The train report is:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3199
           1       1.00      1.00      1.00      3485

    accuracy                           1.00      6684
   macro avg       1.00      1.00      1.00      6684
weighted avg       1.00      1.00      1.00      6684

In [64]:
# Classification report on test data
class_report_test = classification_report(y_test,y_pred)
print ("The test report is:")
print (class_report_test)

The test report is:
              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1371
           1       0.88      0.86      0.87      1494

    accuracy                           0.86      2865
   macro avg       0.86      0.86      0.86      2865
weighted avg       0.86      0.86      0.86      2865

Test set scores are slightly better than before

In [66]:
# Storing the depth of our current model
depth = DT_model.get_depth()
depth

21

In [67]:
# List of max_depth values 
max_depth_list = list(range(depth,0,-3))
max_depth_list

[21, 18, 15, 12, 9, 6, 3]

In [68]:
# Dictionary to store the train and test F1 scores

train_scores = {}
test_scores = {}

# Loop through max_depth values and train the models
for depth in max_depth_list:
    # Initialize the Decision Tree model with the current max_depth value
    DT_model = DecisionTreeClassifier(max_depth=depth, random_state=42, class_weight = 'balanced')
    
    # Train the model
    DT_model.fit(X_train, y_train)
    
    # Make predictions on the train dataset
    y_train_pred = DT_model.predict(X_train)

    # Make predictions on the test dataset
    y_test_pred = DT_model.predict(X_test)
    
    # Store the train F1 score in the dictionary with the max_depth as the key
    train_scores[depth] = f1_score(y_train, y_train_pred)
    
    # Store the test F1 score in the dictionary with the max_depth as the key
    test_scores[depth] = f1_score(y_test, y_test_pred)
    

# Print the train and test F1 scores for each model
for depth in max_depth_list:
    print(f"max_depth = {depth}|\
    Train Score = {train_scores[depth]:.3f} |\
    Test score = {test_scores[depth]:.3f}")
    print('_'*65)

max_depth = 21|    Train Score = 1.000 |    Test score = 0.866
_________________________________________________________________
max_depth = 18|    Train Score = 0.999 |    Test score = 0.862
_________________________________________________________________
max_depth = 15|    Train Score = 0.993 |    Test score = 0.868
_________________________________________________________________
max_depth = 12|    Train Score = 0.970 |    Test score = 0.877
_________________________________________________________________
max_depth = 9|    Train Score = 0.932 |    Test score = 0.887
_________________________________________________________________
max_depth = 6|    Train Score = 0.883 |    Test score = 0.873
_________________________________________________________________
max_depth = 3|    Train Score = 0.822 |    Test score = 0.821
_________________________________________________________________

In [70]:
# Dictionary to store the train and test F1 scores

train_scores = {}
test_scores = {}


# Fill the values in the below list and assign value to the variable!
min_sample_leaf_list = range(1, 11)
depth = 6

# Loop through min_sample_leaf values and train the models
for min_sample_leaf in min_sample_leaf_list:
    
    # Initialize the Decision Tree model with the current min_samples_leaf value
    DT_model = DecisionTreeClassifier(min_samples_leaf=min_sample_leaf, max_depth= depth, random_state=42,  class_weight = 'balanced')
    
    # Train the model
    DT_model.fit(X_train, y_train)
    
    # Make predictions on the train dataset
    y_train_pred = DT_model.predict(X_train)

    # Make predictions on the test dataset
    y_test_pred = DT_model.predict(X_test)
    
    # Store the train F1 score in the dictionary with the min_sample_leaf as the key
    train_scores[min_sample_leaf] = f1_score(y_train, y_train_pred)
    
    # Store the test F1 score in the dictionary with the min_sample_leaf as the key
    test_scores[min_sample_leaf] = f1_score (y_test, y_test_pred)
    

# Print the train and test F1 scores for each model
for min_sample_leaf in min_sample_leaf_list:
    print(f"min_sample_leaf = {min_sample_leaf}|\
    Train Score = {train_scores[min_sample_leaf]:.3f} |\
    Test Score = {test_scores[min_sample_leaf]:.3f}")
    print('_'*65)

min_sample_leaf = 1|    Train Score = 0.883 |    Test Score = 0.873
_________________________________________________________________
min_sample_leaf = 2|    Train Score = 0.883 |    Test Score = 0.874
_________________________________________________________________
min_sample_leaf = 3|    Train Score = 0.883 |    Test Score = 0.873
_________________________________________________________________
min_sample_leaf = 4|    Train Score = 0.882 |    Test Score = 0.873
_________________________________________________________________
min_sample_leaf = 5|    Train Score = 0.882 |    Test Score = 0.874
_________________________________________________________________
min_sample_leaf = 6|    Train Score = 0.882 |    Test Score = 0.873
_________________________________________________________________
min_sample_leaf = 7|    Train Score = 0.882 |    Test Score = 0.872
_________________________________________________________________
min_sample_leaf = 8|    Train Score = 0.882 |    Test Score = 0.872
_________________________________________________________________
min_sample_leaf = 9|    Train Score = 0.882 |    Test Score = 0.873
_________________________________________________________________
min_sample_leaf = 10|    Train Score = 0.881 |    Test Score = 0.873
_________________________________________________________________

min_sample_leaf = 5, depth = 6 leads to the best balanced model in both train and test with f1 score better than earlier models

# Best hyperparameter model

In [71]:
DT_model = DecisionTreeClassifier(min_samples_leaf=5, max_depth=6,random_state=42, class_weight = 'balanced')

In [72]:
DT_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=6, min_samples_leaf=5,
                       random_state=42)

In [73]:
# Making the predictions using the modified X_test
y_pred_train = DT_model.predict(X_train)
y_pred = DT_model.predict(X_test)

In [74]:
#Classification report on train data
class_report_test = classification_report(y_train,y_pred_train)
print ("The train report is:")
print (class_report_test)

The train report is:
              precision    recall  f1-score   support

           0       0.88      0.85      0.87      3199
           1       0.87      0.90      0.88      3485

    accuracy                           0.87      6684
   macro avg       0.88      0.87      0.87      6684
weighted avg       0.88      0.87      0.87      6684

In [75]:
# Classification report on test data
class_report_test = classification_report(y_test,y_pred)
print ("The test report is:")
print (class_report_test)

The test report is:
              precision    recall  f1-score   support

           0       0.87      0.85      0.86      1371
           1       0.87      0.88      0.87      1494

    accuracy                           0.87      2865
   macro avg       0.87      0.87      0.87      2865
weighted avg       0.87      0.87      0.87      2865